### ISSUE TITLE
document command line

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/docs#26]
See https://github.com/x64dbg/x64dbg/issues/210#issuecomment-197227768

**Comment by rmi1974** [comment]
Greetings!

I came across this (from https://github.com/x64dbg/x64dbg/issues/210) because it's actually the only way that works with Wine/Linux.

Using main menu 'File' -> 'Change Command Line' doesn't work, I've documented it in: https://bugs.winehq.org/show_bug.cgi?id=48861

Not sure if the Wine maintainer is keen to have kernelbase.GetCommandLineA/W implementations turned into assembly so that your method works ;-)

**Comment by torusrxxx** [comment]
fc045ee457308a09db31018e4a871927685d72b1
